### ISSUE TITLE
Can not minimize gui to tray

### ISSUE THREAD

**Issue by stoffu** [stoffu/monero-core#1]
https://github.com/monero-project/monero-gui/issues/1163

@BigslimVdub

> Using AEON rebase v1.3 on high Sierra I can not minimize( _ function) to tray. Maximize works fine. Close (x) works fine.
> 
> Running released tar.zip not made with cMake. Tagging @stoffu
> 
> Monero gui 11.0 helium hydra works fine to minimize to tray on same system.

**Comment by stoffu** [comment]
I'll be looking into this, but not in the very near future. Thanks for your patience.

**Comment by BigslimVdub** [comment]
No problem

**Comment by BigslimVdub** [comment]
I still have this issue on 1.7.2.
I just installed XMR 12.0 gui and do not have this issue of minimize with the "custom decorations" turned on. 
On aeon gui, when unchecking the custom decorations box I can minimize with the usual osx buttons.

**Comment by stoffu** [comment]
Thanks for reporting. So, does that mean Monero's GUI and Aeon's GUI behave differently regarding the window minimization on High Sierra? That would be very surprising because the changes I made on top of Monero's GUI are mostly all trivial, e.g. replacing port numbers and changing colors.

**Comment by BigslimVdub** [comment]
Yes, aeon gui 1.7.2 performs different than monero gui 12.0. 

You can get aeon gui to minimize only by deselecting the custom decorations box in settings.

**Comment by stoffu** [comment]
OK, I’ll upgrade one of my Macs to 10.13 and try to reproduce the issue myself.

**Comment by stoffu** [comment]
I've confirmed the same phenomenon with my own 10.13 mac. I did observe the same with my own build of Monero GUI, which means that the cause of this problem is probably in the subtle difference of the build process I did compared to the build done by fluffypony.

At the moment I have no clue how it can be resolved, and I'm not going to prioritize this issue since it's rather minor and probably not due to a programming bug.

**Comment by BigslimVdub** [comment]
It looks like this issue has been resolved with the 0.1.8 pre-release for the GUI in both "custom decorations" mode and "non- custom decorations" modes. 

I would say its good to close this now if others do not have this issue on older OSX versions.

**Comment by stoffu** [comment]
Thanks for reporting. Closing.
