### ISSUE TITLE
"MONERO" label displayed in medium resize state

### ISSUE THREAD

**Issue by TheRealMadmortigan** [stoffu/monero-core#2]
I finally got around to installing the new Aeon beta GUI and noticed a little UI bug.  When re-sizing the window, the "MONERO" name appears while the size is between "small" and "large", we'll call this size, "medium".  Aeon shows correctly in other views.
![aeon_gui](https://user-images.githubusercontent.com/26888597/37227108-1a818130-23aa-11e8-9a4a-3a2f619af1e9.png)

**Comment by stoffu** [comment]
Resolved
