### ISSUE TITLE
restore wallet: from QR code button not working

### ISSUE THREAD

**Issue by VanSenpai** [stoffu/monero-core#4]
Nothing happens and no error message when "From QR Code" button is clicked.
![fromqrcode notworking](https://user-images.githubusercontent.com/38060719/38289667-42185fca-378c-11e8-8ec2-e80b8db584b9.PNG)

**Comment by stoffu** [comment]
Will be resolved eventually when we apply this upstream patch https://github.com/monero-project/monero-gui/pull/1708
